deployments:
  default:
    dockerimage:
      netdata/netdata
    port_forwarding: 80:19999 
    run_options:  --name=netdata -v /proc:/host/proc:ro -v /sys:/host/sys:ro -v /var/run/docker.sock:/var/run/docker.sock:ro --cap-add SYS_PTRACE --security-opt apparmor=unconfined
